#!/bin/bash

check_installed () {
    if ! command -v $1 &> /dev/null
    then
        echo "$1 could not be found"
        exit
    fi
}

if [check_installed chrome]
then
    echo "chrome installed"
else 
    echo "chrome not installed"
fi

# vim

# touch ~/.vimrc
# echo "so ~/dotfiles/nvim/vimrc" > ~/.vimrc

# mkdir ~/.config/nvim/
# touch ~/.config/nvim/init.vim
# echo "so ~/dotfiles/nvim/vimrc" > ~/.config/nvim/init.vim

# # tmux
# mkdir ~/.config/tmux
# touch ~/.config/tmux/tmux.conf
# echo -e "source \"~/dotfiles/tmux/tmux.conf\"" > ~/.config/tmux/tmux.conf

# # lf
# mkdir ~/.config/lf
# touch ~/.config/lf/lfrc
# echo "source ~/dotfiles/lf/lfrc" > ~/.config/lf/lfrc

# # zsh

