" ==================
" RUNTIME
" ==================
set runtimepath^=~/dotfiles/nvim/runtime runtimepath+=~/dotfiles/nvim/runtime/after runtimepath+=~/dotfiles/nvim/runtime/autoload 
let &packpath=&runtimepath

" ==================
" SOURCES
" ==================
so ~/dotfiles/nvim/plugins.vim
so ~/dotfiles/nvim/coc.vim
so ~/dotfiles/nvim/aesthetics.vim

" ==================
" BASIC SETTINGS
" ==================

set nocompatible
set hidden
set wildmenu

set laststatus=2
set mouse=a

syntax enable
filetype plugin on

set tabstop=4
set shiftwidth=4
set nostartofline
set backspace=indent,eol,start

" word wrap
set formatoptions=l
set breakindent
set linebreak

set noswapfile

set number
set cursorline
 
set hlsearch
set incsearch
set ignorecase
set smartcase

set splitbelow
set splitright

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" ==================
" MAPPINGS
" ==================

let mapleader = ","

" avoid the esc key
imap jj <Esc>

" quick save
map <C-s> :w<CR>

" reload vimrc
map <leader>r :so ~/.vimrc<CR> 

" swap lines
map <leader>k :norm ddkkp<CR>
map <leader>j :norm ddp<CR>

" fast indenting
map <S-H> <<
map <S-L> >>

" spellcheck
setlocal spelllang=en_gb
nnoremap <leader>s :set spell<CR>
imap <C-k> <Esc>mz[sz=1<CR>`zi

" easily change filetype
map <leader>ft :set filetype=

" copy and paste to the system clipboard
vnoremap <C-c> "+y
vnoremap <C-x> "+x

" Y behaves like D anc C, ...
map Y y$

"clear prompt also clears highlight
map ; :noh \| echo ""<CR> 

" folding
nnoremap <C-space> za

" cursorline and cursorcolumn
map <leader>- :set invcursorline<CR>
map <leader>\ :set invcursorcolumn<CR>
